### ISSUE TITLE
Next Greater Number

### ISSUE THREAD

**Issue by sharanyakamath** [WebClub-NITK/Hacktoberfest-2k18#13]
### Description
Given a number n, find the smallest number that has same set of digits as n and is greater than n. If x is the greatest possible number with its set of digits, then print “not possible”.

ex:
Input: n = "1234"
Output: "1243"

Input: n = "4321"
Output: "Not Possible"

### Details
- Technical Specifications: C/C++/Python
- Type of issue: Single
- Time Limit: 3 days

### Issue Progress
- [x] C
- [x] C++
- [x] Python

### Directory Structure
Create a folder of the programming language used inside 'algorithms' -->'next_greater_number' folder.
Add your code file inside this folder.
Eg path: `algorithms/next_greater_number/C++/solution.cpp`

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by Aj163** [comment]
I am new to open source, and I think I have all prerequisite knowledge required to solve this issue, and I would like to work on it. Please guide me for the same.

**Comment by SUMUKHA-PK** [comment]
Claiming python.

**Comment by rohit-mp** [comment]
I would like to work on a solution in C

**Comment by sharanyakamath** [comment]
Closing this issue
