### ISSUE TITLE
Add a hello world program in kotlin

### ISSUE THREAD

**Issue by isijara** [WebClub-NITK/Hacktoberfest-2k18#154]
### Description
Add a simple program that outputs "Hello world" 

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by isijara** [comment]
Work in progress

**Comment by pramathabhat** [comment]
I claim!

**Comment by mahim23** [comment]
@isijara Please this is a redundant issue so I'll be closing it.
