### ISSUE TITLE
Responsive Web Design

### ISSUE THREAD

**Issue by nimbus98** [WebClub-NITK/Hacktoberfest-2k18#164]
# Responsive Web Design

![Image of Desktop](https://www.w3schools.com/Css/rwd_desktop.png)  ![Image of Tablet](https://www.w3schools.com/Css/rwd_tablet.png)  ![Image of Phone](https://www.w3schools.com/Css/rwd_phone.png)

Responsive web design (RWD) is an approach to web design that makes web pages render well on a variety of devices and window or screen sizes. Recent work also considers the viewer proximity as part of the viewing context as an extension for RWD. Content, design and performance are necessary across all devices to ensure usability and satisfaction.

### Details
- Technical Specifications: CSS 
- Type of issue: Single
- Time Limit: 2 Days

### Issue requirements / progress
- [ ] Create a CSS file and link it to the html file.
- [ ] Make the webpage responsive.

### Resources
Refer to the README.md provided in the directory.

### Directory Structure

├── development
│   ├── static_to_responsive
│   │   ├── README.md
│   │   ├── static.html

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by 1337M0nst3r** [comment]
Working on this.

**Comment by Prajna12** [comment]
I am working on this!

**Comment by mahim23** [comment]
@Prajna12 the issue has already been assigned to another person. You are welcome to work on some other issue.

**Comment by mishal23** [comment]
Issue resolved.
