### ISSUE TITLE
Loading gradient animation

### ISSUE THREAD

**Issue by utkarsh23** [WebClub-NITK/Hacktoberfest-2k18#199]
### Description
![gradientloader](https://user-images.githubusercontent.com/12075549/46905420-83a13880-cf04-11e8-855f-6b8d6c72fe03.gif)
Sites like Medium and Facebook use gradient loaders as placeholders for actual content until the actual content itself is loaded. Your task is to create a similar gradient loader  **using CSS only**.

### Details
- Technical Specifications: CSS
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements
1. Do not use any frontend frameworks / libraries like Bootstrap. You are free to use other libraries like jquery.
2. Nothing other than the loader itself should be visible on the page and the gradient must move left to right infintely. You are free to make your own choices for any other aspect of the loader (like the time taken by the loader to completely move from left to right once).

### Resources
* [w3schools](https://www.w3schools.com/)
* [codepen](https://codepen.io/)

### Directory Structure
Following is the directory structure to be followed:
```
├── development
│   ├── gradient_loader
│   │   ├── readme.md
│   │   ├── index.html
│   │   ├── index.css
```

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by thomlom** [comment]
Hi, I'm interesting in achieving this task. Has anybody done it so far?

**Comment by MJ10** [comment]
Hi @thomlom you can go ahead and start working on the issue :)

**Comment by thomlom** [comment]
That's done in the PR #202 :slightly_smiling_face:

**Comment by MJ10** [comment]
Issue Resolved
