### ISSUE TITLE
Convert strings to URL Slugs

### ISSUE THREAD

**Issue by mishal23** [WebClub-NITK/Hacktoberfest-2k18#209]
### Description
Many content management sites (CMS) have the titles of a post added to part of the URL for simple bookmarking purposes. For example, if you write a Medium post titled "How to use Github", it's likely the URL would have some form of the title string in it (".../how-to-use-github").

Write a function in Javascript such that it converts a string `title` and returns the hyphenated version for the URL.
**Usage of `replace` is not allowed**

### Details
- Technical Specifications: Javascript
- Type of issue: Single
- Time Limit: 2 days

### Resources
- [Split](https://www.w3schools.com/jsref/jsref_split.asp)
- [Filter](https://www.w3schools.com/jsref/jsref_filter.asp)
- [Join](https://www.w3schools.com/jsref/jsref_join.asp)
- [Regex](https://www.w3schools.com/jsref/jsref_obj_regexp.asp)

### Directory Structure
Make sure the following directory structure is followed
```
.
└── development
    └── string_to_url_slug
        ├── file.js
        └── README.md
```
#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by SergiyGolov** [comment]
Hi, can I start working on this issue?

**Comment by mishal23** [comment]
@SergiyGolov yes sure.

**Comment by SergiyGolov** [comment]
I've made a pull request, is my code OK for you?
