### ISSUE TITLE
Horizontal line loader animation

### ISSUE THREAD

**Issue by utkarsh23** [WebClub-NITK/Hacktoberfest-2k18#22]
### Description
![youtube loader image](https://user-images.githubusercontent.com/12075549/46380566-59f44000-c6c0-11e8-8529-cd3d02188dde.png)
Sites like Medium, YouTube and Flickr use a horizontal line loading animation along the topmost edge of the web page. Recreate this animation effect for 6 seconds in the following manner:
* first 3 seconds, loader moves from 0% to 60%
* loader stalls for 1 second
* in the last two seconds it moves from 60% to 100%
* after 350ms, the loader vanishes.

### Details
- Technical Specifications: CSS/JS
- Type of issue: Single
- Time Limit: 2 days

### Issue requirements
1. Do not use any frontend frameworks / libraries like Bootstrap. You are free to use other libraries like jquery.
2. Nothing other than the animation should be visible on the page.
3. The loader must move from one point to the next with a transition like ease, linear or any other transition of your choice.

### Resources
* [w3schools](https://www.w3schools.com/)
* [codepen](https://codepen.io/)

### Directory Structure
Following is the directory structure to be followed:
```bash
├── development
│   ├── horizontal_loader
│   │   ├── readme.md
│   │   ├── index.html
│   │   ├── index.css
│   │   ├── index.js
```

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by stuajnht** [comment]
Hi,

I'd like to work on this issue please.

**Comment by utkarsh23** [comment]
@stuajnht sure you can
create a pull request referencing this issue
