### ISSUE TITLE
Image search in bash terminal

### ISSUE THREAD

**Issue by utkarsh23** [WebClub-NITK/Hacktoberfest-2k18#23]
### Description
![catpix image](http://radek.io/assets/images/posts/catpix/panda.png)
[catpix](https://github.com/pazdera/catpix) is a very interesting tool that renders images in your bash terminal. Your task is to write a shell script to input a user query and `n` - number of results that the user wants to see (max 10). So with [catpix](https://github.com/pazdera/catpix) and any image search API ([Bing](https://azure.microsoft.com/en-in/services/cognitive-services/bing-image-search-api/)) you will then display top `n` results in the bash terminal.

### Details
- Technical Specifications: bash script
- Type of issue: Single
- Time Limit: 4 days

### Issue Requirements
1. Input at least two things from the user, the query and the number of results that the user wants to see.
2. If you wish to provide additional options to the user like resolution of images, scaling etc. you are free to do so.
3. Mention all the prerequisites to using catpix in `readme.md` and also add appropriate comments in your code. Ensure that your code is clearly and easily readable.
4. Ensure that your bash script cleans up the folder after printing all images.

### Resources
* [catpix](https://github.com/pazdera/catpix)
* [Bing Image Search API](https://azure.microsoft.com/en-in/services/cognitive-services/bing-image-search-api/)
* [ImageMagick](https://www.imagemagick.org/script/index.php)
* [rmagick](https://rubygems.org/gems/rmagick)

### Directory Structure
```bash
├── development
│   ├── bash_image_search
│   │   ├── readme.md
│   │   ├── image_search.sh
```

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by cemysf** [comment]
Hi, I would like to work on this

**Comment by utkarsh23** [comment]
@cemysf sure you can
create a pull request referencing this issue
