### ISSUE TITLE
Implement Caesar Cipher

### ISSUE THREAD

**Issue by aditigupta17** [WebClub-NITK/Hacktoberfest-2k18#27]
### Description
The Caesar Cipher technique is one of the earliest and simplest method of encryption technique. It’s simply a type of substitution cipher, i.e., each letter of a given text is replaced by a letter some fixed number of positions down the alphabet. For example with a shift of 1, A would be replaced by B, B would become C, and so on. 

Thus to cipher a given text we need an integer value, known as shift which indicates the number of position each letter of the text has been moved down.
The encryption can be represented using modular arithmetic by first transforming the letters into numbers, according to the scheme, A = 0, B = 1,…, Z = 25.

#### Input:
- A String of lower case letters, called Text.
- An Integer between 0-25 denoting the required shift.

You are expected to write a program that receives a Text (string) and Shift value( integer) and returns the encrypted text.

### Details
Technical Specifications:
- Type of issue: No more than one implementation will be accepted for each language. Once the implementation for a language has been taken up (i.e if it is checked in the 'Issue Progress' section), you must choose from the remaining.
- Time Limit: Issues will be given on a first-come, first-serve basis. Once you take this issue up, you must complete it within 2 days, failing which the issue will be allocated to the next person who requested for this issue.
- Additional instructions: While making the Pull Request, attach screenshots of 5 sample inputs and their corresponding output.

### Issue requirements / progress
- [x] C
- [x] C++
- [x] Python
- [x] Java  

### Resources
https://learncryptography.com/classical-encryption/caesar-cipher

### Directory Structure
For this issue, use the following directory of the Hacktoberfest-2k18 repository:
/systems/cryptography/caesar-cipher/language_name
(where language_name is one of the languages mentioned above.)

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by shakeelsamsu** [comment]
Working on a solution in Java!

**Comment by SUMUKHA-PK** [comment]
Claiming python.

**Comment by singleparadox** [comment]
Claiming C

**Comment by mahim23** [comment]
@singleparadox Thank you for your interest but the C implementation has already been submitted and merged. Please work on some other implementation.
