### ISSUE TITLE
Implement Diffie-Hellman Key Exchange Algorithm

### ISSUE THREAD

**Issue by aditigupta17** [WebClub-NITK/Hacktoberfest-2k18#28]
### Description
The Diffie-Hellman algorithm is being used to establish a shared secret that can be used for secret communications while exchanging data over a public network using the elliptic curve to generate points and get the secret key using the parameters.

#### Explanation:
For the sake of simplicity and practical implementation of the algorithm, we will consider only 4 variables, one prime P and G (a primitive root of P) and two private values a and b.
P and G are both publicly available numbers. Users (say Alice and Bob) pick private values a and b and they generate a key and exchange it publicly, the opposite person received the key and from that generates a secret key after which they have the same secret key to encrypt.

You are expected to write a program to generate a random prime number P and take one of its primitive root G, and then generate random numbers a, b and generate secret key after exchange of keys. You are free to choose any programming language for your choice for the implementation of same.

### Details
Technical Specifications:
- Type of issue: No more than one implementation will be accepted for each language. Once the implementation for a language has been taken up (i.e if it is checked in the 'Issue Progress' section), you must choose from the remaining.
- Time Limit: Issues will be given on a first-come, first-serve basis. Once you take this issue up, you must complete it within 2 days, failing which the issue will be allocated to the next person who requested for this issue.
- Additional instructions: While making the Pull Request, attach screenshots of 5 sample inputs and their corresponding output.

### Issue requirements / progress
- [x] C
- [x] C++
- [x] Python
- [x] Java  

### Resources
https://hackernoon.com/algorithms-explained-diffie-hellman-1034210d5100

### Directory Structure
For this issue, use the following directory of the Hacktoberfest-2k18 repository:
/systems/cryptography/diffie-hellman/language_name
(where language_name is one of the languages mentioned above.)

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by SUMUKHA-PK** [comment]
Claiming python

**Comment by deepakkavoor** [comment]
I would like to claim this issue

**Comment by Ram-Aditya** [comment]
@SUMUKHA-PK  Sorry but since you haven't submitted a PR within the time limit, the implementation in Python will now be handed over to the next person requesting it. Although, you can request to claim the issue for C, C++ or Python.

**Comment by SUMUKHA-PK** [comment]
Sorry but I had pending PRs in other directories and I can submit one at a time so I didnt work on it until they were cleared. Im claiming Python again.

**Comment by Ram-Aditya** [comment]
@SUMUKHA-PK  Yes sure, go ahead. But please make sure to follow the time limit.

**Comment by SUMUKHA-PK** [comment]
Thanks.
Please do merge the above too.

**Comment by pramathabhat** [comment]
I would like to work on this issue in Java

**Comment by prprhyt** [comment]
I claim C.

**Comment by aditigupta17** [comment]
@prprhyt Go ahead.
