### ISSUE TITLE
Implement RSA Algorithm

### ISSUE THREAD

**Issue by aditigupta17** [WebClub-NITK/Hacktoberfest-2k18#29]
### Description
RSA algorithm is asymmetric cryptography algorithm. Asymmetric actually means that it works on two different keys i.e. Public Key and Private Key. As the name describes that the Public Key is given to everyone and Private key is kept private.

An example of asymmetric cryptography :
A client (for example browser) sends its public key to the server and requests for some data.
The server encrypts the data using client’s public key and sends the encrypted data.
Client receives this data and decrypts it.

Since this is asymmetric, nobody else except browser can decrypt the data even if a third party has public key of browser.

#### Task: 
You are expected to generate a dummy data, encrypt it using RSA Algorithm and decrypt it.

### Details
Technical Specifications:
- Type of issue: No more than one implementation will be accepted for each language. Once the implementation for a language has been taken up (i.e if it is checked in the 'Issue Progress' section), you must choose from the remaining.
- Time Limit: Issues will be given on a first-come, first-serve basis. Once you take this issue up, you must complete it within 2 days, failing which the issue will be allocated to the next person who requested for this issue.
- Additional instructions: While making the Pull Request, attach screenshots of 5 sample inputs and their corresponding output.

### Issue requirements / progress
- [x] C
- [x] C++
- [x] Java
- [x] Python 

### Resources
https://www.di-mgt.com.au/rsa_alg.html

### Directory Structure
For this issue, use the following directory of the Hacktoberfest-2k18 repository:
/systems/cryptogrphy/rsa/language_name
(where language_name is one of the languages mentioned above.)

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by SUMUKHA-PK** [comment]
Claiming python.

**Comment by mahim23** [comment]
@SUMUKHA-PK you can start working on it.

**Comment by rajat1433** [comment]
claiming C++

**Comment by rajat1433** [comment]
Already submitted a pull request also.

**Comment by aditigupta17** [comment]
@rajat1433 you can work on it.

**Comment by pramathabhat** [comment]
Claiming Java

**Comment by PoojithaR** [comment]
i claim

**Comment by mehnazyunus** [comment]
Hi, I'd like to work on the C implementation.

**Comment by aditigupta17** [comment]
Go ahead.
