### ISSUE TITLE
Application of Kfolds on Single Layered Perceptron using the iris dataset.

### ISSUE THREAD

**Issue by shreyasseshadri** [WebClub-NITK/Hacktoberfest-2k18#89]
### Description
Implement a Single Layered Perceptron on the iris dataset with k-fold cross validation without the use of libraries that contain implementation of the same.

### Details
- Technical Specifications: Python
- Type of issue: Single (Only the python implementaion is considered).
- Time Limit: 3 days

### Issue requirements / progress
- [ ] Plot the accuracy and loss over the iterations within each fold.
- [ ] Find the accuracy of the model with each fold.

### Resources
- [Resource on SLP](https://www.computing.dcu.ie/~humphrys/Notes/Neural/single.neural.html)
- [Resource on K-Fold Cross Validation](https://en.wikipedia.org/wiki/Cross-validation_(statistics))

### Directory Structure
Name the code file as <your_name>.py and save it inside this folder.

```
machine_learning/kfolds_cross_validation/<your_name>.py
```

#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by Manask322** [comment]
I would like to work on this issue
