### ISSUE TITLE
Implement Binary Search

### ISSUE THREAD

**Issue by sharanyakamath** [WebClub-NITK/Hacktoberfest-2k18#92]
### Description
Implement binary search in any programming language of your choice.

### Details
- Technical Specifications: Any programming language
- Type of issue: Multiple
- Time Limit: 2 days

### Resources
Learn more about binary search [here.](https://en.wikipedia.org/wiki/Binary_search_algorithm)

### Issue Requirements
- [x] C
- [x] Java
- [x] Ruby
- [x] Python

### Directory Structure
Create a folder of your programming language inside binary_search folder in algorithms folder. Add your file in this folder and name it as <your_name>.extension.
Eg: `algorithms/binary_search/cpp/sharanya.cpp
`
#### Note
Please claim the issue first by commenting here before starting to work on it.

**Comment by cesargralmeida** [comment]
Implemented Binary Search in Ruby

**Comment by v-chmykov** [comment]
Implementing Binary Search in Python

**Comment by PoojithaR** [comment]
I claim!!

**Comment by Prajna12** [comment]
I have implemented this using python.

**Comment by mahim23** [comment]
@PoojithaR @Prajna12 Sorry but this issue has been resolved completely. I'll be closing it now.
